apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api-creditos-consulta
  description: Microservicio de consulta de creditos hipotecarios
  labels:
    country: cl
    capability: prestamos
    portfolio: tecnologico
    equipo: teamDev
  tags:
    - rest
    - go
  links:
    - url: http://RFC
      title: RFC
      icon: docs
    - url: https://app.datadoghq.com/dashboard/mfy-amg-bss/integraciones-cl-consolidada
      title: APM DataDog
      icon: dashboard
spec:
  type: service
  owner: group:fiftech_integraciones_country
  lifecycle: pre-production
  system: prestamos
  providesApis:
    - api-creditos-consulta
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-creditos-consulta-api
  description: API definition for api-creditos-consulta
  labels:
    country: cl
    portfolio: tecnologico
    equipo: teamDev
  tags:
    - api
  links:
    - url: http://apicurio
      title: Apicurio
      icon: docs
spec:
  type: openapi
  owner: group:fiftech_integraciones
  lifecycle: pre-production
  system: prestamos
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: API Creditos Consulta
    servers:
      - url: http://integracion-k8s-dev.fif.tech
      - url: http://integracion-k8s-qa.fif.tech
    paths:
      /api/creditos/consulta/:
        post:
          summary: Consulta creditos asociados a un RUT
